### ISSUE TITLE
Set-gpiopin not working as expected

### ISSUE THREAD

**Issue by jaswalters** [PowerShell/PowerShell-IoT#44]
I set everything up on the pi and built a small led circuit on a breadboard with gpio #18. I run 
set-gpiopin -id 18 -value High and the Led does nothing.

I try the same via python code and works no issues. 

Am I missing something here?

**Comment by TylerLeonhardt** [comment]
@jaswalters can you do me a favor and double check you have the right pin?

https://github.com/PowerShell/PowerShell-IoT/blob/master/docs/rpi3_pin_layout.md

**Comment by jaswalters** [comment]
@TylerLeonhardt  TY! That did it. I saw that diagram a while back but did not put the correlation together.

**Comment by TylerLeonhardt** [comment]
No worries! Enjoy your PowerShell powered hardware 😎
