### ISSUE TITLE
impact of 'wiringPI - deprecated' as this library is build on top if it?

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell-IoT#48]
[Deprecate annoncement](http://wiringpi.com/wiringpi-deprecated/)
> I will make a final release of wiringPi available soon – with the sources, but that’s that. No more public releases. I’ll still be maintaining it for my own uses and clients, but for everyone else, please look at for alternative GPIO library for on-going projects.
> 
> -Gordon, August, 2019
Is an alternative GPIO library considered to replace wiringPI ?

**Comment by TylerLeonhardt** [comment]
Yep, we plan to move to https://github.com/dotnet/iot but haven't gotten around to it. @DanielSSilva was starting it/going to start it but I'm not sure how far he got.

**Comment by DanielSSilva** [comment]
Hi!
Yes I've started to port our current cmdlets to use a new library. We will be using the dotnet IoT repo for that.
I've successfully implemented the I2C using this library, without braking anything.
As for the gpio, there will be some breaking changes (I expect to create an issue and documentation for that). I've started to implement that but there are some issues that are being addressed with the dotnet IoT team.
You can see the progress on the branch forked from the master (I'm on mobile and can't link it)
