### ISSUE TITLE
Change of pin layout

### ISSUE THREAD

**Issue by DanielSSilva** [PowerShell/PowerShell-IoT#49]
With the migration to the [dotnet/iot](https://github.com/dotnet/iot) framework, breaking changes will be introduced.
For this case, the dotnet team uses same layout that's used by the python library. This means that from now on, the pin Ids will match those in that library. Another reason is that the wiringpi has been [officially deprecated](http://wiringpi.com/wiringpi-deprecated/)
As a suggestion, [here's the website](https://pinout.xyz/) that I use to check the pin ids.

**Comment by TylerLeonhardt** [comment]
I think this is a necessary breaking change given the circumstance we just need to make sure we update our docs accordingly.

**Comment by DanielSSilva** [comment]
Before changing the text of this issue I've wrote this, and forgot to leave it here.

> This is just to keep track and discussed such breaking changes. Those will be listed on the changelog when we release a new version to the gallery.
In this case, both changelog and our docs
